# Generated by Django 2.2.8 on 2020-01-05 10:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_href', models.TextField(max_length=10)),
                ('index', models.IntegerField()),
                ('href_index', models.CharField(default='<django.db.models.fields.TextField>[<django.db.models.fields.IntegerField>]', editable=False, max_length=20, unique=True)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
                ('word', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('word_imi', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_href', models.CharField(max_length=10, unique=True)),
                ('video_img', models.CharField(max_length=20)),
                ('video_time', models.CharField(max_length=10)),
                ('video_title', models.CharField(max_length=50)),
                ('video_genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('youtubeID', models.CharField(max_length=20)),
                ('video_upload_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_ini', models.CharField(max_length=1)),
                ('word', models.CharField(max_length=50, unique=True)),
                ('word_imi', models.CharField(default='default', max_length=120)),
            ],
        ),
    ]
