# Generated by Django 2.2.7 on 2019-12-01 10:21

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_href', models.TextField(max_length=10)),
                ('index', models.IntegerField()),
                ('href_index', models.CharField(default='<django.db.models.fields.TextField>[<django.db.models.fields.IntegerField>]', editable=False, max_length=20, unique=True)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
                ('word', jsonfield.fields.JSONField(default=[])),
                ('word_imi', jsonfield.fields.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_href', models.CharField(max_length=10, unique=True)),
                ('video_img', models.CharField(max_length=20)),
                ('video_time', models.CharField(max_length=10)),
                ('video_title', models.CharField(max_length=50)),
                ('youtubeID', models.CharField(max_length=20)),
                ('video_update_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_ini', models.CharField(max_length=1)),
                ('word', models.CharField(max_length=50, unique=True)),
                ('word_imi', models.CharField(default='default', max_length=120)),
            ],
        ),
    ]
