# Generated by Django 2.2.8 on 2020-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_upload_date',
            field=models.DateField(),
        ),
    ]
