# Generated by Django 2.2.8 on 2020-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0002_auto_20200110_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_upload_date',
            field=models.DateTimeField(),
        ),
    ]
