# Generated by Django 2.2.8 on 2020-01-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0002_fetchsetting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchsetting',
            name='user',
            field=models.CharField(default='1', max_length=30, unique=True),
        ),
    ]
