# Generated by Django 2.2.8 on 2020-01-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0003_auto_20200110_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='href_index',
            field=models.CharField(default='<django.db.models.fields.CharField>[<django.db.models.fields.IntegerField>]', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='caption',
            name='video_href',
            field=models.CharField(max_length=10),
        ),
    ]
