# Generated by Django 2.2.8 on 2020-01-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0006_auto_20200118_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='href_index',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>[<django.db.models.fields.IntegerField>]', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='caption',
            name='video_href',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_console.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_href',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
