# Generated by Django 2.2.8 on 2020-01-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0007_auto_20200125_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchsetting',
            name='language_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='minimum_sentence',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='page_to_crawl',
            field=models.IntegerField(default=5),
        ),
    ]
