# Generated by Django 2.2.8 on 2020-01-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0007_auto_20200118_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caption',
            name='href_index',
        ),
    ]
