# Generated by Django 2.2.8 on 2020-01-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0008_remove_caption_href_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='video_href',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_console.Video', to_field='video_href'),
        ),
    ]
