# Generated by Django 2.2.8 on 2020-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0009_auto_20200119_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoExcepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_href', models.CharField(max_length=10, unique=True)),
                ('video_img', models.CharField(max_length=20)),
                ('video_title', models.CharField(max_length=50)),
                ('youtubeID', models.CharField(max_length=20)),
            ],
        ),
    ]
