# Generated by Django 2.2.8 on 2020-01-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0010_videoexcepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoexcepted',
            name='youtubeID',
        ),
    ]
