# Generated by Django 2.2.8 on 2020-01-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0011_remove_videoexcepted_youtubeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoexcepted',
            name='video_img',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videoexcepted',
            name='video_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
