# Generated by Django 2.2.10 on 2020-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchsetting',
            name='video_per_page',
            field=models.IntegerField(default=10),
        ),
    ]
