# Generated by Django 3.0.4 on 2020-03-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordappearance',
            old_name='video_href',
            new_name='video',
        ),
    ]
