# Generated by Django 2.2.10 on 2020-02-15 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0002_fetchsetting_video_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='end_time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='caption',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caption',
            name='start_time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='language_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='minimum_sentence',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='page_to_crawl',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='video_per_page',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
