# Generated by Django 2.2.8 on 2020-01-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0003_auto_20200125_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fetchsetting',
            old_name='crowled_page',
            new_name='page_to_crawl',
        ),
    ]
