# Generated by Django 2.2.10 on 2020-02-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0004_auto_20200215_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caption',
            name='video_href',
        ),
        migrations.DeleteModel(
            name='FetchSetting',
        ),
        migrations.RemoveField(
            model_name='wordappearance',
            name='word',
        ),
        migrations.DeleteModel(
            name='Caption',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='WordAppearance',
        ),
    ]
