# Generated by Django 2.2.8 on 2020-01-25 11:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0005_auto_20200125_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchsetting',
            name='excepted_href',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='video_to_delete',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='video_to_renewal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, null=True, size=None),
        ),
    ]
