# Generated by Django 3.0.4 on 2020-03-19 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0005_auto_20200320_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='meanings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.CharField(default='', max_length=200),
        ),
    ]
