# Generated by Django 2.2.8 on 2020-01-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0006_auto_20200125_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchsetting',
            name='language_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='minimum_sentence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='page_to_crawl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fetchsetting',
            name='user',
            field=models.CharField(default='super', max_length=30, unique=True),
        ),
    ]
