# Generated by Django 2.2.10 on 2020-02-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0006_caption_fetchsetting_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_ini', models.CharField(max_length=1)),
                ('word', models.CharField(max_length=50, unique=True)),
                ('word_imi', models.CharField(default='default', max_length=120)),
            ],
        ),
    ]
