# Generated by Django 2.2.10 on 2020-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0007_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_imi',
            field=models.CharField(default='', max_length=120),
        ),
    ]
