# Generated by Django 2.2.10 on 2020-02-23 09:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0008_auto_20200223_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('word_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dictionary_console.Word')),
            ],
        ),
    ]
