# Generated by Django 3.0.3 on 2020-02-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0009_wordappearance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordappearance',
            old_name='word_id',
            new_name='word',
        ),
    ]
