# Generated by Django 3.0.5 on 2020-04-11 10:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0010_auto_20200411_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='word_pairs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
