# Generated by Django 3.0.6 on 2020-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0017_auto_20200512_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='excepted',
            field=models.BooleanField(default=False),
        ),
    ]
