# Generated by Django 3.0.6 on 2020-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0022_auto_20200520_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionword',
            name='fixed_word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
