# Generated by Django 3.0.6 on 2020-05-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0023_auto_20200520_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionword',
            name='root_word',
            field=models.ForeignKey(db_column='word', on_delete=django.db.models.deletion.CASCADE, to='dictionary_console.Word'),
        ),
    ]
