# Generated by Django 3.0.6 on 2020-05-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0025_auto_20200520_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='captionword',
            name='fixed_meaning',
            field=models.CharField(default='', max_length=200),
        ),
    ]
