# Generated by Django 3.0.6 on 2020-05-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_console', '0018_video_excepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='excepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='want',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
