# Generated by Django 3.0.4 on 2020-03-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caption",
            name="text",
            field=models.CharField(max_length=200),
        ),
    ]
