# Generated by Django 3.0.4 on 2020-03-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0002_auto_20200319_0008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caption",
            name="text",
            field=models.CharField(max_length=500),
        ),
    ]
