# Generated by Django 3.0.4 on 2020-03-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0003_auto_20200319_0216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fetchsetting",
            name="authority",
            field=models.CharField(
                blank=True, default="super", max_length=30, null=True, unique=True
            ),
        ),
    ]
