# Generated by Django 3.0.4 on 2020-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0004_auto_20200319_0258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fetchsetting",
            name="authority",
            field=models.CharField(
                blank=True, default="super", max_length=30, unique=True
            ),
        ),
    ]
