# Generated by Django 3.0.4 on 2020-03-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0006_auto_20200320_0127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordappearance",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary_console.Word",
                to_field="word",
            ),
        ),
    ]
