# Generated by Django 3.0.5 on 2020-04-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0008_auto_20200322_2143"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordappearance",
            name="video_href",
        ),
        migrations.AddField(
            model_name="caption",
            name="unique_id",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="wordappearance",
            name="appearance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary_console.Caption",
                to_field="unique_id",
            ),
        ),
    ]
