# Generated by Django 3.0.5 on 2020-04-21 10:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0012_auto_20200411_2245"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caption",
            name="word_pairs",
        ),
        migrations.AddField(
            model_name="caption",
            name="meanings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), default=[], size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="caption",
            name="words",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
