# Generated by Django 3.0.6 on 2020-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0014_auto_20200502_1511"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["-published_at"]},
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_upload_date",
        ),
        migrations.AddField(
            model_name="video",
            name="published_at",
            field=models.CharField(default="", max_length=50),
        ),
    ]
