# Generated by Django 3.0.6 on 2020-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0016_video_want"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="want",
            field=models.BooleanField(default=True),
        ),
    ]
