# Generated by Django 3.0.6 on 2020-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0019_auto_20200512_0325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="excepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="video",
            name="want",
            field=models.BooleanField(default=True),
        ),
    ]
