# Generated by Django 3.0.6 on 2020-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0021_auto_20200520_1032"),
    ]

    operations = [
        migrations.RenameField(
            model_name="captionword",
            old_name="word",
            new_name="root_word",
        ),
        migrations.AddField(
            model_name="captionword",
            name="fixed_word",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
