# Generated by Django 3.0.6 on 2020-05-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0024_auto_20200520_2007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captionword",
            name="root_word",
            field=models.ForeignKey(
                db_column="word_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary_console.Word",
            ),
        ),
    ]
