# Generated by Django 3.0.6 on 2020-05-23 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0026_captionword_fixed_meaning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captionword",
            name="caption",
            field=models.ForeignKey(
                db_column="caption_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary_console.Caption",
            ),
        ),
    ]
