# Generated by Django 3.0.6 on 2020-05-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0027_auto_20200523_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captionword",
            name="root_word",
            field=models.ForeignKey(
                blank=True,
                db_column="word_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary_console.Word",
            ),
        ),
    ]
