# Generated by Django 3.2 on 2021-05-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary_console", "0029_remove_caption_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
